spring:
# use environment variables for database configuration in production, with defaults for local development
#  datasource:
#    url: jdbc:postgresql://${DB_HOST:postgres-db}:${DB_PORT:5432}/${DB_NAME}
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
  datasource:
    url: jdbc:postgresql://localhost:5432/clothing_ecommerce_db
    username: ecommerce_admin
    password: super_secret_password_123
  jpa:
    hibernate:
      ddl-auto: update # Use 'validate' in actual production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Custom properties for Tableau Connected Apps
tableau:
  server-url: "https://prod-useast-a.online.tableau.com" # Example Tableau Cloud URL
  client-id: "YOUR_CONNECTED_APP_CLIENT_ID"
  secret-id: "YOUR_CONNECTED_APP_SECRET_ID"
  secret-value: "YOUR_CONNECTED_APP_SECRET_VALUE"