spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/clothing_ecommerce_db
    username: ecommerce_admin
    password: super_secret_password_123
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Custom properties for Tableau Connected Apps - Updated with your live credentials
tableau:
  server-url: "https://prod-in-a.online.tableau.com" 
  client-id: "f7becdd8-0bf3-40e4-92bc-acd834830700"
  secret-id: "45edd21c-78e0-4615-8d01-1b3ce87ed408"
  secret-value: "q6ySKZujfE+VpctKm/PVoHus1vANT9Z0RO+Y+c1lKmk="